export const FETCH_STATEDATE = "FETCH_STATEDATE";
export const FETCH_AUTHENTICATION = "FETCH_AUTHENTICATION";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const OBTENER_FACTURASPAGOSEXTERNOS = "OBTENER_FACTURASPAGOSEXTERNOS";
export const INICIAR_SESION = "INICIAR_SESION";


//URL backend

export const URL_PRINCIPAL = "http://localhost:21200/api/"